sudo: required

services:
  - docker

env:
  matrix:
    - CI_ROS_DISTRO="melodic"
    - CI_ROS_DISTRO="noetic"

install:
  - docker build -t imu_tools_$CI_ROS_DISTRO -f Dockerfile-$CI_ROS_DISTRO .

script:
  - docker run imu_tools_$CI_ROS_DISTRO /bin/bash -c "source devel/setup.bash && catkin run_tests && catkin_test_results"
